# Generated by Django 5.2 on 2025-04-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elektrikhat',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='kanalhat',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='oyunalan',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='park',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='parkabone',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='parkbina',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='parkdonati',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='parkoyungrup',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='sporalan',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='sulamahat',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='sulamanokta',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='yesilalan',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
    ]
