# Generated by Django 5.2 on 2025-04-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0002_alter_elektrikhat_osm_id_alter_habitat_osm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='ad',
            field=models.CharField(help_text='Park adı giriniz.', max_length=50, verbose_name='Park Adı'),
        ),
    ]
