# Generated by Django 5.2 on 2025-04-25 08:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0003_alter_park_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElektrikBaglantiTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Elektrik bağlantı tipi giriniz.', max_length=50, unique=True, verbose_name='Elektrik Bağlantı Tipi')),
                ('aciklama', models.TextField(blank=True, help_text='Elektrik bağlantı tipi hakkında açıklama giriniz.', null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Elektrik Bağlantı Tipi',
                'verbose_name_plural': 'Elektrik Bağlantı Tipleri',
                'db_table': '"parkbahce"."elektrik_baglanti_tipleri"',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='ElektrikNoktaTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Elektrik noktası tipi giriniz.', max_length=50, unique=True, verbose_name='Elektrik Noktası Tipi')),
                ('aciklama', models.TextField(blank=True, help_text='Elektrik noktası tipi hakkında açıklama giriniz.', null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Elektrik Noktası Tipi',
                'verbose_name_plural': 'Elektrik Noktası Tipleri',
                'db_table': '"parkbahce"."elektrik_noktasi_tipleri"',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='ElektrikNokta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Elektrik noktasını belirten geometri alanı.', srid=5256, verbose_name='Geometri')),
                ('extra_data', models.JSONField(blank=True, help_text='Elektrik noktası ile ilgili ekstra verileri JSON formatında giriniz.', null=True, verbose_name='Ekstra Veri')),
                ('osm_id', models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('elektrik_baglanti_tipi', models.ForeignKey(blank=True, help_text='Elektrik bağlantı tipi seçiniz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elektrik_noktalar', to='parkbahce.elektrikbaglantitip', verbose_name='Elektrik Bağlantı Tipi')),
                ('park', models.ForeignKey(help_text='Elektrik noktasının bulunduğu park.', on_delete=django.db.models.deletion.CASCADE, related_name='elektrik_noktalar', to='parkbahce.park', verbose_name='Park')),
                ('elektrik_nokta_tipi', models.ForeignKey(blank=True, help_text='Elektrik noktası tipi seçiniz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elektrik_noktalar', to='parkbahce.elektriknoktatip', verbose_name='Elektrik Noktası Tipi')),
            ],
            options={
                'verbose_name': 'Elektrik Noktası',
                'verbose_name_plural': 'Elektrik Noktaları',
                'db_table': '"parkbahce"."elektrik_noktalar"',
            },
        ),
    ]
