# Generated by Django 5.2 on 2025-04-30 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0005_alter_elektrikhat_uuid_alter_elektriknokta_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SporAletiGrup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Spor aleti grubunu giriniz.', max_length=50, unique=True, verbose_name='Spor Aleti Grubu')),
                ('aciklama', models.TextField(blank=True, help_text='Spor aleti grubu hakkında açıklama giriniz.', null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Spor Aleti Grubu',
                'verbose_name_plural': 'Spor Aleti Grupları',
                'db_table': '"parkbahce"."spor_aleti_gruplari"',
                'ordering': ['ad'],
            },
        ),
        migrations.AddField(
            model_name='oyunalan',
            name='oyun_grup_tipi',
            field=models.ForeignKey(blank=True, help_text='Oyun grubu tipi seçiniz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oyun_alanlar', to='parkbahce.oyungruptip', verbose_name='Oyun Grubu Tipi'),
        ),
        migrations.AddField(
            model_name='sporalan',
            name='spor_aleti_grup',
            field=models.ForeignKey(blank=True, help_text='Spor aleti grubunu seçiniz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spor_alanlar', to='parkbahce.sporaletigrup', verbose_name='Spor Aleti Grubu'),
        ),
    ]
