# Generated by Django 5.2 on 2025-04-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0006_sporaletigrup_oyunalan_oyun_grup_tipi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OyunGrupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Oyun grubu modeli giriniz.', max_length=50, unique=True, verbose_name='Oyun Grubu Modeli')),
                ('aciklama', models.TextField(blank=True, help_text='Oyun grubu modeli hakkında açıklama giriniz.', null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Oyun Grubu Modeli',
                'verbose_name_plural': 'Oyun Grubu Modelleri',
                'db_table': '"parkbahce"."oyun_grubu_modelleri"',
                'ordering': ['ad'],
            },
        ),
        migrations.AddField(
            model_name='oyunalan',
            name='oyun_grup_model',
            field=models.ForeignKey(blank=True, help_text='Oyun grubu modeli seçiniz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oyun_alanlar', to='parkbahce.oyungrupmodel', verbose_name='Oyun Grubu Modeli'),
        ),
    ]
