# Generated by Django 5.2 on 2025-04-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0007_oyungrupmodel_oyunalan_oyun_grup_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oyunalan',
            name='oyun_grup_model',
        ),
        migrations.RemoveField(
            model_name='oyunalan',
            name='oyun_grup_tipi',
        ),
        migrations.AddField(
            model_name='parkoyungrup',
            name='oyun_grup_model',
            field=models.ForeignKey(blank=True, help_text='Oyun grubu modeli seçiniz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oyun_alanlar', to='parkbahce.oyungrupmodel', verbose_name='Oyun Grubu Modeli'),
        ),
    ]
