# Generated by Django 5.2 on 2025-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0008_remove_oyunalan_oyun_grup_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elektriknokta',
            name='sayi',
            field=models.IntegerField(blank=True, default=1, help_text='Elektrik noktasının sayısını giriniz.', null=True, verbose_name='Elektrik Noktası Sayısı'),
        ),
    ]
