# Generated by Django 5.2 on 2025-05-07 11:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0009_elektriknokta_sayi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkHavuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Havuz sınırlarını belirten geometri alanı.', srid=5256, verbose_name='Geometri')),
                ('alan', models.FloatField(blank=True, default=0, help_text='Havuz alanını giriniz.', null=True, verbose_name='Alan')),
                ('cevre', models.FloatField(blank=True, default=0, help_text='Havuz çevresini giriniz.', null=True, verbose_name='Çevre')),
                ('extra_data', models.JSONField(blank=True, help_text='Havuz ile ilgili ekstra verileri JSON formatında giriniz.', null=True, verbose_name='Ekstra Veri')),
                ('osm_id', models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('park', models.ForeignKey(help_text='Havuzun bulunduğu park.', on_delete=django.db.models.deletion.CASCADE, related_name='havuzlar', to='parkbahce.park', verbose_name='Park')),
            ],
            options={
                'verbose_name': 'Havuz',
                'verbose_name_plural': 'Havuzlar',
                'db_table': '"parkbahce"."havuzlar"',
            },
        ),
    ]
