# Generated by Django 5.2.1 on 2025-05-23 07:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0010_parkhavuz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkYol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('yol_tipi', models.CharField(blank=True, help_text='Yol tipini giriniz.', max_length=50, null=True, verbose_name='Yol Tipi')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Yol sınırlarını belirten geometri alanı.', srid=5256, verbose_name='Geometri')),
                ('alan', models.FloatField(blank=True, default=0, help_text='Yol alanını giriniz.', null=True, verbose_name='Alan')),
                ('extra_data', models.JSONField(blank=True, help_text='Yol ile ilgili ekstra verileri JSON formatında giriniz.', null=True, verbose_name='Ekstra Veri')),
                ('osm_id', models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('park', models.ForeignKey(help_text='Yolun bulunduğu park.', on_delete=django.db.models.deletion.CASCADE, related_name='yollar', to='parkbahce.park', verbose_name='Park')),
            ],
            options={
                'verbose_name': 'Yol',
                'verbose_name_plural': 'Yollar',
                'db_table': '"parkbahce"."yollar"',
            },
        ),
    ]
