# Generated by Django 5.2.1 on 2025-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0012_donatitip_deger_elektrikbaglantitip_deger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewParklarDonatilarHabitatlar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(editable=False, help_text='Park için benzersiz tanımlayıcı.', unique=True, verbose_name='UUID')),
                ('ad', models.CharField(max_length=255, verbose_name='Park Adı')),
                ('habitatlar', models.JSONField(default=dict, help_text='Parka ait habitat verilerinin tutulduğu JSON alanı.', verbose_name='Habitatlar')),
                ('donatilar', models.JSONField(default=dict, help_text='Parka ait donatı verilerinin tutulduğu JSON alanı.', verbose_name='Donatılar')),
            ],
            options={
                'verbose_name': 'Parklar Donatılar Habitatlar',
                'verbose_name_plural': 'Parklar Donatılar Habitatlar',
                'db_table': '"parkbahce"."view_parklar_donatilar_habitatlar"',
                'ordering': ['ad'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='parkabone',
            options={'ordering': ['park__ad', 'abone_tipi', 'abone_no'], 'verbose_name': 'Park Abone', 'verbose_name_plural': 'Park Aboneleri'},
        ),
    ]
