# Generated by Django 5.2.1 on 2025-06-24 05:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0013_viewparklardonatilarhabitatlar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkabone',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Abone noktasını belirten geometri alanı.', null=True, srid=5256, verbose_name='Geometri'),
        ),
    ]
