# Generated by Django 5.2.1 on 2025-06-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0014_alter_parkabone_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkabone',
            name='ilk_endeks',
            field=models.FloatField(blank=True, help_text='Abonenin ilk endeks değerini giriniz.', null=True, verbose_name='İlk Endeks'),
        ),
    ]
