# Generated by Django 5.2.1 on 2025-06-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkbahce', '0015_parkabone_ilk_endeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkabone',
            name='ilk_endeks',
            field=models.FloatField(blank=True, default=0.0, help_text='Abonenin ilk endeks değerini giriniz.', null=True, verbose_name='İlk Endeks'),
        ),
    ]
