# Generated by Django 5.2 on 2025-04-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ortak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ada',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='il',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='ilce',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='mahalle',
            name='osm_id',
            field=models.CharField(blank=True, help_text="OpenStreetMap'den alınan benzersiz kimlik.", max_length=50, null=True, unique=True, verbose_name='OSM ID'),
        ),
    ]
