# Generated by Django 5.2.1 on 2025-06-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorev',
            name='tamamlanma_tarihi',
            field=models.DateTimeField(blank=True, help_text='Görevin tamamlanma tarihini giriniz.', null=True, verbose_name='Tamamlanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='gorevasama',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('baslamadi', 'Başlamadı'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı')], default='baslamadi', help_text='Aşamanın durumunu seçiniz.', max_length=20, verbose_name='Durum'),
        ),
    ]
