# Generated by Django 5.2.1 on 2025-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0002_gorev_tamamlanma_tarihi_alter_gorevasama_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorev',
            name='onay_tarihi',
            field=models.DateTimeField(blank=True, help_text='Görevin onaylandığı tarihi giriniz.', null=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='durum',
            field=models.CharField(choices=[('planlanmis', 'Planlanmış'), ('devam_ediyor', 'Devam Ediyor'), ('onaya_gonderildi', 'Onaya Gönderildi'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal'), ('gecikmis', 'Gecikmiş')], default='planlanmis', help_text='Görevin durumunu seçiniz.', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='gunlukkontrol',
            name='durum',
            field=models.CharField(choices=[('sorun_yok', 'Sorun Yok'), ('sorun_var', 'Sorun Var'), ('acil', 'Acil Müdahale Gerekli'), ('gozden_gecirildi', 'Gözden Geçirildi'), ('ise_donusturuldu', 'İşe Dönüştürüldü'), ('cozuldu', 'Çözüldü')], help_text='Parkın durumunu seçiniz.', max_length=20, verbose_name='Durum'),
        ),
    ]
